// Write code below 💖
console.log("=============================================");
console.log("          Kentucky fried chicken        ");
console.log("---------------------------------------------");
console.log("              Order Details              ");
console.log("---------------------------------------------");
console.log("Item        Quantity                Price");
console.log("---------------------------------------------");
console.log("Burger          1                    3.99");
console.log("Pizza           4                    10.03");
console.log("Fried chicken   4                    12.02");
console.log("---------------------------------------------");
console.log("Total                                37.0");
console.log("=============================================");
