
const Answer = Math.floor(Math.random() * 9) + 1;
if (Answer === 1) {
  console.log("Yes - definitely.");
} else if (Answer === 2) {
  console.log("It is decidedly so.");
} else if (Answer === 3) {
  console.log("Without a doubt.");
} else if (Answer === 4) {
  console.log("Reply hazy, try again.");
} else if (Answer === 5) {
  console.log("Ask again later.");
} else if (Answer === 6) {
  console.log("Better not tell you now.");
} else if (Answer === 7) {
  console.log("My sources say no.");
} else if (Answer === 8) {
  console.log("Outlook not so good.");
} else {
  console.log("Very doubtful.");
}
